version: '3.8'

services:
  flask:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - keycloak

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - flask

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/opt/keycloak/realm-export.json
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realm-export.json:/opt/keycloak/realm-export.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
