version: '3.8'

services:
  flask:
    build: .
    container_name: flask
    networks:
      - backend
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - keycloak

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - flask
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge