version: '3.8'

services:
  flask:
    build: .
    container_name: flask
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - flask
      - keycloak
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
     command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HTTP_RELATIVE_PATH=/auth
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
